namespace UndercoverGame.Services;
using UndercoverGame.Models;

public static class WordBank
{
    public static List<WordPair> pairs = new List<WordPair>
    {
        new WordPair { CivilianWord = "Cat", UndercoverWord = "Dog" },
        new WordPair { CivilianWord = "Apple", UndercoverWord = "Banana" },
        new WordPair { CivilianWord = "Car", UndercoverWord = "Bike" },
        new WordPair { CivilianWord = "Sun", UndercoverWord = "Moon" },
        new WordPair { CivilianWord = "Coffee", UndercoverWord = "Tea" },
        new WordPair { CivilianWord = "Pen", UndercoverWord = "Pencil" },
        new WordPair { CivilianWord = "Chair", UndercoverWord = "Table" },
        new WordPair { CivilianWord = "River", UndercoverWord = "Lake" },
        new WordPair { CivilianWord = "Bird", UndercoverWord = "Fish" },
        new WordPair { CivilianWord = "Book", UndercoverWord = "Magazine" },
        new WordPair { CivilianWord = "Inception", UndercoverWord = "Interstellar" },
        new WordPair { CivilianWord = "Titanic", UndercoverWord = "The Notebook" },
        new WordPair { CivilianWord = "Avatar", UndercoverWord = "Dune" },
        new WordPair { CivilianWord = "Joker", UndercoverWord = "The Batman" },
        new WordPair { CivilianWord = "Frozen", UndercoverWord = "Tangled" },
        new WordPair { CivilianWord = "The Matrix", UndercoverWord = "Blade Runner" },
        new WordPair { CivilianWord = "Gladiator", UndercoverWord = "Troy" },
        new WordPair { CivilianWord = "Harry Potter", UndercoverWord = "Percy Jackson" },
        new WordPair { CivilianWord = "The Avengers", UndercoverWord = "Justice League" },
        new WordPair { CivilianWord = "Finding Nemo", UndercoverWord = "Moana" },

        new WordPair { CivilianWord = "Shape of You", UndercoverWord = "Perfect" },
        new WordPair { CivilianWord = "Blinding Lights", UndercoverWord = "Starboy" },
        new WordPair { CivilianWord = "Someone Like You", UndercoverWord = "Hello" },
        new WordPair { CivilianWord = "Bad Guy", UndercoverWord = "Therefore I Am" },
        new WordPair { CivilianWord = "Levitating", UndercoverWord = "Don't Start Now" },
        new WordPair { CivilianWord = "Stay", UndercoverWord = "Ghost" },
        new WordPair { CivilianWord = "Happier", UndercoverWord = "Closer" },
        new WordPair { CivilianWord = "Counting Stars", UndercoverWord = "Apologize" },
        new WordPair { CivilianWord = "Senorita", UndercoverWord = "Havana" },
        new WordPair { CivilianWord = "Believer", UndercoverWord = "Thunder" },

        new WordPair { CivilianWord = "Python", UndercoverWord = "JavaScript" },
        new WordPair { CivilianWord = "React", UndercoverWord = "Vue" },
        new WordPair { CivilianWord = "MySQL", UndercoverWord = "PostgreSQL" },
        new WordPair { CivilianWord = "Docker", UndercoverWord = "Kubernetes" },
        new WordPair { CivilianWord = "Git", UndercoverWord = "SVN" },
        new WordPair { CivilianWord = "Linux", UndercoverWord = "Unix" },
        new WordPair { CivilianWord = "AWS", UndercoverWord = "Azure" },
        new WordPair { CivilianWord = "REST API", UndercoverWord = "GraphQL" },
        new WordPair { CivilianWord = "HTML", UndercoverWord = "XML" },
        new WordPair { CivilianWord = "Flask", UndercoverWord = "Django" },

        new WordPair { CivilianWord = "Neuron", UndercoverWord = "Synapse" },
        new WordPair { CivilianWord = "Atom", UndercoverWord = "Molecule" },
        new WordPair { CivilianWord = "Virus", UndercoverWord = "Bacteria" },
        new WordPair { CivilianWord = "DNA", UndercoverWord = "RNA" },
        new WordPair { CivilianWord = "Gravity", UndercoverWord = "Magnetism" },
        new WordPair { CivilianWord = "Speed", UndercoverWord = "Velocity" },
        new WordPair { CivilianWord = "Energy", UndercoverWord = "Power" },
        new WordPair { CivilianWord = "Heat", UndercoverWord = "Temperature" },
        new WordPair { CivilianWord = "Mass", UndercoverWord = "Weight" },
        new WordPair { CivilianWord = "Light", UndercoverWord = "Photon" },

        new WordPair { CivilianWord = "King", UndercoverWord = "Emperor" },
        new WordPair { CivilianWord = "Soldier", UndercoverWord = "Mercenary" },
        new WordPair { CivilianWord = "Police", UndercoverWord = "Detective" },
        new WordPair { CivilianWord = "Judge", UndercoverWord = "Lawyer" },
        new WordPair { CivilianWord = "Doctor", UndercoverWord = "Surgeon" },
        new WordPair { CivilianWord = "Teacher", UndercoverWord = "Professor" },
        new WordPair { CivilianWord = "Pilot", UndercoverWord = "Captain" },
        new WordPair { CivilianWord = "Chef", UndercoverWord = "Cook" },
        new WordPair { CivilianWord = "Artist", UndercoverWord = "Designer" },
        new WordPair { CivilianWord = "Writer", UndercoverWord = "Author" },

        new WordPair { CivilianWord = "Love", UndercoverWord = "Obsession" },
        new WordPair { CivilianWord = "Fear", UndercoverWord = "Anxiety" },
        new WordPair { CivilianWord = "Happiness", UndercoverWord = "Joy" },
        new WordPair { CivilianWord = "Anger", UndercoverWord = "Rage" },
        new WordPair { CivilianWord = "Truth", UndercoverWord = "Reality" },
        new WordPair { CivilianWord = "Lie", UndercoverWord = "Deception" },
        new WordPair { CivilianWord = "Dream", UndercoverWord = "Fantasy" },
        new WordPair { CivilianWord = "Memory", UndercoverWord = "Flashback" },
        new WordPair { CivilianWord = "Hope", UndercoverWord = "Faith" },
        new WordPair { CivilianWord = "Freedom", UndercoverWord = "Liberty" },

        new WordPair { CivilianWord = "Football", UndercoverWord = "Rugby" },
        new WordPair { CivilianWord = "Cricket", UndercoverWord = "Baseball" },
        new WordPair { CivilianWord = "Tennis", UndercoverWord = "Badminton" },
        new WordPair { CivilianWord = "Basketball", UndercoverWord = "Netball" },
        new WordPair { CivilianWord = "Swimming", UndercoverWord = "Diving" },
        new WordPair { CivilianWord = "Running", UndercoverWord = "Jogging" },
        new WordPair { CivilianWord = "Boxing", UndercoverWord = "MMA" },
        new WordPair { CivilianWord = "Cycling", UndercoverWord = "Motorcycling" },
        new WordPair { CivilianWord = "Golf", UndercoverWord = "Mini Golf" },
        new WordPair { CivilianWord = "Chess", UndercoverWord = "Checkers" },

        new WordPair { CivilianWord = "Pizza", UndercoverWord = "Burger" },
        new WordPair { CivilianWord = "Tea", UndercoverWord = "Coffee" },
        new WordPair { CivilianWord = "Rice", UndercoverWord = "Noodles" },
        new WordPair { CivilianWord = "Cake", UndercoverWord = "Pastry" },
        new WordPair { CivilianWord = "Ice Cream", UndercoverWord = "Gelato" },
        new WordPair { CivilianWord = "Chocolate", UndercoverWord = "Candy" },
        new WordPair { CivilianWord = "Soup", UndercoverWord = "Stew" },
        new WordPair { CivilianWord = "Sandwich", UndercoverWord = "Wrap" },
        new WordPair { CivilianWord = "Pancake", UndercoverWord = "Waffle" },
        new WordPair { CivilianWord = "Sushi", UndercoverWord = "Sashimi" },

        new WordPair { CivilianWord = "Earth", UndercoverWord = "Mars" },
        new WordPair { CivilianWord = "Sun", UndercoverWord = "Star" },
        new WordPair { CivilianWord = "Moon", UndercoverWord = "Satellite" },
        new WordPair { CivilianWord = "Galaxy", UndercoverWord = "Universe" },
        new WordPair { CivilianWord = "Ocean", UndercoverWord = "Sea" },
        new WordPair { CivilianWord = "River", UndercoverWord = "Stream" },
        new WordPair { CivilianWord = "Mountain", UndercoverWord = "Hill" },
        new WordPair { CivilianWord = "Forest", UndercoverWord = "Jungle" },
        new WordPair { CivilianWord = "Desert", UndercoverWord = "Dune" },
        new WordPair { CivilianWord = "Island", UndercoverWord = "Continent" },

        new WordPair { CivilianWord = "Password", UndercoverWord = "PIN" },
        new WordPair { CivilianWord = "Encryption", UndercoverWord = "Hashing" },
        new WordPair { CivilianWord = "Firewall", UndercoverWord = "Antivirus" },
        new WordPair { CivilianWord = "Hacker", UndercoverWord = "Cracker" },
        new WordPair { CivilianWord = "Phishing", UndercoverWord = "Spoofing" },
        new WordPair { CivilianWord = "Malware", UndercoverWord = "Virus" },
        new WordPair { CivilianWord = "Exploit", UndercoverWord = "Payload" },
        new WordPair { CivilianWord = "VPN", UndercoverWord = "Proxy" },
        new WordPair { CivilianWord = "Token", UndercoverWord = "Session" },
        new WordPair { CivilianWord = "Authentication", UndercoverWord = "Authorization" }
    };

    public static WordPair GetRandom()
    {
        var rng = new Random();
        return pairs[rng.Next(pairs.Count)];
    }
}